name: SDL2 GNUBoy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install libs
      run: 
        sudo apt-get update
        sudo apt-get install libsdl2-dev
    - name: make
      run: make
